### ISSUE TITLE
Refactor code related to thresholding visibility weights

### ISSUE THREAD

**Issue by sjforeman** [radiocosmology/draco#201]
We now have `ThresholdVisWeights` and `ThresholdVisWeightsTime`, and will have `ThresholdVisWeightsBaseline` after https://github.com/radiocosmology/draco/pull/200 is merged. These should be refactored in an intelligent way.

**Comment by ljgray** [comment]
It's easy to refactor `ThresholdVisWeights` and `ThresholdVisWeightsTime` but it will be trickier with `ThresholdVisWeightBaseline` since it applies in-place rather than returning a mask. We could add a baseline-dependent mask container (if it doesn't already exist) and a task similar to `ApplyRFIMask` which applies a baseline-dependent mask, since it seems like something that we will be doing in multiple places from time to time.

**Comment by sjforeman** [comment]
I'm working on a solution that could replace both `ThresholdVisWeightTime` and `ThresholdVisWeightBaseline`, which would be flexible enough to use at multiple points in the daily processing. I'll post a draft PR for your consideration soon

**Comment by jrs65** [comment]
I'm pretty resistant to baseline dependent masks unless there's some demonstrable benefit.

For all the problems we are dealing with it seems like the data loss incurred from turning a baseline dependent mask into an independent one (by masking all baselines if you would have masked one). I think we at least need to find a case where that is not true to consider making such a change.

**Comment by sjforeman** [comment]
I have 3 cases in mind here:
1. `ThresholdVisWeightBaseline`, which applies a baseline-dependent mask in place.
2. `ThresholdVisWeightTime`, which effectively constructs a baseline-dependent mask but then masks all baselines at any freq/time sample for which any baseline is flagged.
3. The equivalent of `ThresholdVisWeightTime` but taking a median along the frequency axis to construct the mask. This will be necessary to catch some of the issues I've seen in rev_03.

With the appropriate relative threshold, I've found indications that `ThresholdVisWeightBaseline` could catch all the samples that are masked by points 2 and 3 above, *if* it masked all baselines at any time/freq time sample for which any baseline was masked. I also think it would be useful to be able to output the mask produced by `ThresholdVisWeightBaseline` before it is applied, so we can examine what is going on instead of just having the mask applied in place to the input stream.

So, I am proposing the following:
1. Make new `BaselineMask` containers to hold baseline-dependent masks.
2. Modify `ThresholdVisWeightBaseline` to output a baseline-dependent mask, with the option to have the mask applied in-place to the input stream.
3. Make a task (`CollapseBaselineMask`) that collapses a `BaselineMask` into an `RFIMask`, for cases where we only want a time/freq mask.

With these changes in place, we could apply `ThresholdVisWeightBaseline` + `CollapseBaselineMask` to chimestack files to flag out the artifacts I discussed last week, and apply `ThresholdVisWeightBaseline` later in the pipeline, with in-place masking turned on, to deal with artifacts from the regridder.

**Comment by ljgray** [comment]
With the updates Simone made in #203, I'm not sure if this issue is relevant anymore, as `ThresholdVisWeightBaseline` and `ThresholdVisWeightFreq` are different enough that trying to combine them into one task would get messy (plus one returns a non-distributed mask while the other returns a distributed one). 

@sjforeman obviously the reason for keeping/reintroducing the old `ThresholdVisWight` was because the new one didn't accomplish what we needed it to. If this new baseline-specific task can accomplish the same thing, then we probably don't have to reintroduce the old version/we can remove it again since #200 was merged.

**Comment by sjforeman** [comment]
I was under the impression that the version of `ThresholdVisWeightBaseline` in #200 is just a stopgap until there is a better scheme to mitigate what the regridder does to the weights. If the better scheme still looks something like the #200 scheme, then the #203 routine might be applicable. I suppose we might have to wait and see...

**Comment by sjforeman** [comment]
#203 has been merged, but now we have `ThresholdVisWeightBaseline` and `ThresholdVisWeightBaselineAlt`, so there is still some refactoring to be done. (Perhaps the former task can also be used in place of the latter, by setting thresholds appropriately, but I haven't tested this...)

**Comment by ljgray** [comment]
I'm pretty sure that `ThresholdVisWeightBaseline` will produce the same mask as `ThresholdVisWeightBaselineAlt`, although I don't think we technically have a task to apply the non-collapsed mask. I'm going to test it a bit to be sure.
