### ISSUE TITLE
Support adding datasets to a container that has been loaded from a file

### ISSUE THREAD

**Issue by ssiegelx** [radiocosmology/draco#290]
Currently the `draco.core.ContainerBase.add_dataset` method fails if the container has been instantiated with the `from_file` method.

The reason for the failure is because the `allow_chunked` attribute does not exist.  The `allow_chunked` attribute is set in the [`ContainerBase.__init__`](https://github.com/radiocosmology/draco/blob/533da7513de42c5eb6395ea28edb594f60d685a0/draco/core/containers.py#L166) method, which the `from_file` method explicitly avoids calling ([see here](https://github.com/radiocosmology/caput/blob/09fb81ee16c198a74fc42ebafa96371ad8cad77f/caput/memh5.py#L1866)).

If `allow_chunked = True` (default) then the `add_dataset` method uses the chunk options specified in a containers `_dataset_spec` attribute.  If it's `False`, then the chunk size is not specified.  As far as I can tell, nowhere in the code base is a container instantiated with `allow_chunked = False`.

If I make `allow_chunked` a class attribute that defaults to `True`, then loading the data from a file and then adding a new dataset appears to work fine.

I'm not very familiar with the inner workings of `caput.memh5`.  Are you aware of any subtle issues with adding datasets to a container that has been loaded from disk?

If not, how should the `allow_chunked` attribute be set?

**Comment by tristpinsm** [comment]
IIRC `allow_chunked` only exists so that you can disable compression as it was not supported in some instances. So I think it not being created when the container is instantiated through `from_file` is just an oversight, and making it a class attribute should be harmless.

I don't know of any subtle issues when adding datasets to a container loaded from disk. My understanding is that once it is in memory it is just like any other container. If it is not in memory (`ondisk=True`) then things may be different but I'm not sure how it behaves.

**Comment by ljgray** [comment]
I agree with Tristan. I don't anticipate any issues with making `allow_chunked` a class attribute.

**Comment by ljgray** [comment]
This was closed by #291
