### ISSUE TITLE
Insert version and config into the "history"

### ISSUE THREAD

**Issue by jrs65** [radiocosmology/draco#88]
`BasicCont` object have a `.history` section, this is where we should have added the version and config tracking, and so we should put them there (using the `.add_history(...)` call), rather than in the root metadata.

**Comment by nritsche** [comment]
The way `.(add_)history` works at the moment is that it takes single-level dictionaries and uses their key/value pairs as attributes to the groups under the "history" group.
Unfortunately this single-level dict serialization clashes with the multi-level dict serialization I added in https://github.com/radiocosmology/caput/commit/9272c10a81bf3d2fd98f14fb59df7d83116f8321 if we want to add for example the config to `.history`.

I propose to change the `BasicCont.history` to have attributes (instead of groups) whose values would get fully serialized and de-serialized by caput when writing/reading from disk. This would break backward compatibility somewhat. But as @jrs65 proposed, we could continue to support reading files in the old format. Files written after this change will look different though (a prefix is added to signal that a string is a serialized json). Would that work for you, @kiyo-masui ?

**Comment by jrs65** [comment]
@kiyo-masui just pinging you again. I want to make sure we're not going to clobber any functionality the FRB folks use if we change that implementation.

**Comment by kiyo-masui** [comment]
Despite me having the foresight to add history tracking to memh5, I don't think anyone has every used it for anything. You are all clear to change it.

**Comment by jrs65** [comment]
It was indeed genius level foresight that was completely unappreciated in its time. It's only after reinventing the same thing that we really appreciate the wisdom of the ancient ones.

Also, thanks!
